"""add refresh_token key for users

Revision ID: 6b4dda79d926
Revises: dadc753a956a
Create Date: 2019-04-12 12:59:03.965672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b4dda79d926'
down_revision = 'dadc753a956a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('refresh_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'refresh_token')
    # ### end Alembic commands ###
