"""add expiration timestamp to user model

Revision ID: 7ac635a9b8bb
Revises: 6b4dda79d926
Create Date: 2019-04-12 13:34:00.444405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ac635a9b8bb'
down_revision = '6b4dda79d926'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('expiration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'expiration')
    # ### end Alembic commands ###
