"""add course_id to assignment

Revision ID: 8256df210df2
Revises: 7ac635a9b8bb
Create Date: 2019-04-15 14:08:58.955355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8256df210df2'
down_revision = '7ac635a9b8bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment', sa.Column('course_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment', 'course_id')
    # ### end Alembic commands ###
