"""create new sequential ID for outcome primary key

Revision ID: bc4519596133
Revises: ba0d3f6d8cc9
Create Date: 2019-12-09 09:48:33.123831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc4519596133'
down_revision = 'ba0d3f6d8cc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outcome', sa.Column('outcome_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outcome', 'outcome_id')
    # ### end Alembic commands ###
