"""remove association table, add course_id to Outcome

Revision ID: de6c9ce558a9
Revises: 8256df210df2
Create Date: 2019-04-25 10:18:29.128872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de6c9ce558a9'
down_revision = '8256df210df2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alignments')
    op.add_column('outcome', sa.Column('course_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outcome', 'course_id')
    op.create_table('alignments',
    sa.Column('outcome_id', sa.INTEGER(), nullable=True),
    sa.Column('assignment_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.id'], ),
    sa.ForeignKeyConstraint(['outcome_id'], ['outcome.id'], )
    )
    # ### end Alembic commands ###
