"""remove last_section key for now

Revision ID: ee57394e52d2
Revises: 88510f7d95e7
Create Date: 2019-08-08 10:40:17.744061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee57394e52d2'
down_revision = '88510f7d95e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('last_section', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'last_section')
    # ### end Alembic commands ###
